spring:
    application:
        name: eureka

server:
    port: 9091

eureka:
    instance:
        hostname: agent1.com
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
#            defaultZone: http://agent2.com:9092/eureka/
            defaultZone: http://agent2.com:9092/eureka/,http://agent3.com:9093/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
